# Generated by Django 4.2 on 2025-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicin', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, unique=True)),
                ('herbs', models.ManyToManyField(related_name='remedies', to='medicin.herb')),
            ],
        ),
    ]
